// Expo config plugin: strips network permissions from release builds (CLAUDE.md guardrail 1).
// Debug and dev-client builds keep INTERNET so Metro can serve the JS bundle. Release builds get a
// variant manifest that marks each permission tools:node="remove", so the manifest merger drops it
// even when a library manifest adds it back. CI checks the built APK for these permissions.
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const NETWORK_PERMISSIONS = [
  'android.permission.INTERNET',
  'android.permission.ACCESS_NETWORK_STATE',
  'android.permission.ACCESS_WIFI_STATE',
  'android.permission.CHANGE_NETWORK_STATE',
  'android.permission.CHANGE_WIFI_STATE',
];

function releaseManifest() {
  const lines = NETWORK_PERMISSIONS.map(
    (p) => `  <uses-permission android:name="${p}" tools:node="remove"/>`,
  );
  return [
    '<!-- Generated by plugins/withReleaseNoNetwork.js. Do not edit. -->',
    '<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">',
    ...lines,
    '</manifest>',
    '',
  ].join('\n');
}

const withReleaseNoNetwork = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'release');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), releaseManifest());
      return cfg;
    },
  ]);

module.exports = withReleaseNoNetwork;
module.exports.NETWORK_PERMISSIONS = NETWORK_PERMISSIONS;
